#
###################################
# Site wide configuration
####################################
#
title: Fromis_9 Fan Page
email: imreplay@imreplay.xyz
description: Fromis_9 Fan Page.
url: https://fromis9.kr # the base hostname & protocol for your site
keywords: ["fromis9", "fromis_9",]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Fromis_9 Fan Page
  avatar: logo.jpg
  job: 
  bio: 
  email: imreplay@imreplay.xyz
  disqus-shortname: fromis9
  twitter: imreplay0822 #username
  facebook: imreplay08 #username
  google:
    plus: #username
    analytics: UA-120523980-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
